services:
    # examspractice:
    #     image: adeoluadeyemi/examspractice:1.0.0
    #     ports:
    #         - '80:80'
    #     volumes:
    #         - './.env:/var/www/html/.env'
    #         # - './docker/nginx.conf:/etc/nginx/nginx.conf'
    #     networks:
    #         - dev
    #     depends_on:
    #         - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './database/mysql:/var/lib/mysql'
        networks:
            - dev
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8082:80
        networks:
            - dev
        environment:
            - PMA_ARBITRARY=1
networks:
    dev:
        driver: bridge

# volumes:
#     mysql:
#         driver: local
